---
- hosts: localhost
  become: yes
  become_user: davemus
  pre_tasks:
    - name: downloading files to jenkins
      get_url:
        url: "{{ source }}/{{ beats }}/{{ beats }}-{{ version }}-x86_64.rpm"
        dest: /tmp
       

- hosts: linux
  become: yes
  roles:
    - role-beatinstall

- hosts: localhost
  become: yes
  become_user: davemus
  post_tasks:
    - name: deleting downloaded files
      file: 
        path: "/tmp/{{ beats }}-{{ version }}-x86_64.rpm"
        state: absent
